[package]
name = "galliary-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-web-lab = "0.10"
actix-cors = "0.6"
juniper = "0.15"
env_logger = "0.9"
log = "0.4"
serde_json = "1"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "1.4.8", features = ["postgres"] }
dotenv = "0.15.0"