//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use async_graphql::*;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Enum, Copy, Eq,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "SafetyRating")]
pub enum SafetyRating {
    #[sea_orm(string_value = "MATURE")]
    Mature,
    #[sea_orm(string_value = "NOT_SAFE")]
    NotSafe,
    #[sea_orm(string_value = "SAFE")]
    Safe,
    #[sea_orm(string_value = "TRUSTED")]
    Trusted,
    #[sea_orm(string_value = "UNKNOWN")]
    Unknown,
}
#[derive(
    Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Enum, Copy, Eq,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "LockingStatus")]
pub enum LockingStatus {
    #[sea_orm(string_value = "HIDDEN")]
    Hidden,
    #[sea_orm(string_value = "LOCKED")]
    Locked,
    #[sea_orm(string_value = "NONE")]
    None,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "NotificationType")]
pub enum NotificationType {
    #[sea_orm(string_value = "ALBUM_DELETED_BY_MODERATOR")]
    AlbumDeletedByModerator,
    #[sea_orm(string_value = "ALBUM_LOCKED_BY_MODERATOR")]
    AlbumLockedByModerator,
    #[sea_orm(string_value = "ALBUM_UNLOCKED_BY_MODERATOR")]
    AlbumUnlockedByModerator,
    #[sea_orm(string_value = "GROUP_MEMBER_INVITE_ACCEPTED")]
    GroupMemberInviteAccepted,
    #[sea_orm(string_value = "GROUP_MEMBER_INVITE_DECLINED")]
    GroupMemberInviteDeclined,
    #[sea_orm(string_value = "GROUP_MEMBER_INVITE_EXPIRED")]
    GroupMemberInviteExpired,
    #[sea_orm(string_value = "GROUP_MEMBER_JOINED")]
    GroupMemberJoined,
    #[sea_orm(string_value = "GROUP_MEMBER_LEFT")]
    GroupMemberLeft,
    #[sea_orm(string_value = "IMAGE_DELETED_BY_MODERATOR")]
    ImageDeletedByModerator,
    #[sea_orm(string_value = "IMAGE_LOCKED_BY_MODERATOR")]
    ImageLockedByModerator,
    #[sea_orm(string_value = "IMAGE_UNLOCKED_BY_MODERATOR")]
    ImageUnlockedByModerator,
    #[sea_orm(string_value = "NEW_FAVOURITE")]
    NewFavourite,
    #[sea_orm(string_value = "NEW_FOLLOWER")]
    NewFollower,
    #[sea_orm(string_value = "NEW_GROUP_INVITE")]
    NewGroupInvite,
    #[sea_orm(string_value = "RANDOM_INFO")]
    RandomInfo,
    #[sea_orm(string_value = "SUBSCRIPTION_ACTIVE")]
    SubscriptionActive,
    #[sea_orm(string_value = "SUBSCRIPTION_EXPIRED")]
    SubscriptionExpired,
    #[sea_orm(string_value = "SUBSCRIPTION_EXPIRING_SOON")]
    SubscriptionExpiringSoon,
    #[sea_orm(string_value = "USER_MARKED_AS_MATURE_BY_MODERATOR")]
    UserMarkedAsMatureByModerator,
    #[sea_orm(string_value = "USER_MARKED_AS_NOT_MATURE_BY_MODERATOR")]
    UserMarkedAsNotMatureByModerator,
    #[sea_orm(string_value = "USER_MARKED_AS_NOT_TRUSTED_BY_MODERATOR")]
    UserMarkedAsNotTrustedByModerator,
    #[sea_orm(string_value = "USER_MARKED_AS_TRUSTED_BY_MODERATOR")]
    UserMarkedAsTrustedByModerator,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "ModeratorNotificationsType"
)]
pub enum ModeratorNotificationsType {
    #[sea_orm(string_value = "NEW_REPORT")]
    NewReport,
    #[sea_orm(string_value = "SUSPICIOUS_ACTIVITY")]
    SuspiciousActivity,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "UserConnectionType")]
pub enum UserConnectionType {
    #[sea_orm(string_value = "DISCORD")]
    Discord,
    #[sea_orm(string_value = "EMAIL")]
    Email,
    #[sea_orm(string_value = "GOOGLE")]
    Google,
    #[sea_orm(string_value = "LINKEDIN")]
    Linkedin,
    #[sea_orm(string_value = "TWITTER")]
    Twitter,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "UserRole")]
pub enum UserRole {
    #[sea_orm(string_value = "ADMINISTRATOR")]
    Administrator,
    #[sea_orm(string_value = "MATURE")]
    Mature,
    #[sea_orm(string_value = "MODERATOR")]
    Moderator,
    #[sea_orm(string_value = "NONE")]
    None,
    #[sea_orm(string_value = "NOT_SAFE")]
    NotSafe,
    #[sea_orm(string_value = "SAFE")]
    Safe,
    #[sea_orm(string_value = "SUPERADMIN")]
    Superadmin,
    #[sea_orm(string_value = "TRUSTED")]
    Trusted,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "GroupMemberRole")]
pub enum GroupMemberRole {
    #[sea_orm(string_value = "ADMINISTRATOR")]
    Administrator,
    #[sea_orm(string_value = "NONE")]
    None,
    #[sea_orm(string_value = "OWNER")]
    Owner,
}
